[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
    -DWIFI_LOGGING_ENABLE=1
    -DWIFI_LOGGING_UDP_IP=\"192.168.0.249\"
    -DWIFI_LOGGING_UDP_PORT=10514
    -I include

